-- 매출목표 마스터(신규, DB-28: 레거시 부재). 대시보드 목표 대비 실적용.
-- (연도, 월, 상품) 단위 목표. product_id=NULL이면 전사 월목표.
CREATE TABLE sales_target (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fiscal_year   INT    NOT NULL,
    month         INT    NOT NULL CHECK (month BETWEEN 1 AND 12),
    product_id    BIGINT REFERENCES products(id),   -- NULL=전사 월목표
    target_amount BIGINT NOT NULL,
    created_at    TIMESTAMP NOT NULL,
    created_by    VARCHAR(50),
    updated_at    TIMESTAMP,
    updated_by    VARCHAR(50)
);
-- (연도,월,상품) 유일. NULL 상품은 COALESCE(-1)로 하나만 허용.
CREATE UNIQUE INDEX ux_sales_target ON sales_target (fiscal_year, month, COALESCE(product_id, -1));
