-- =============================================================================
-- V1 — 자체 도메인 코어 스키마
--   상품/BOM · 창고/재고 · 출고유형 룩업 · 위탁 미결정산 · 채번
-- 근거: 요구사항정의서 시트2(데이터·업무로직 정의) + reference/legacy DDL 대조
--   🆕 = 레거시에 없던 신규 (창고/원가/BOM비율/미결정산/감사 등)
-- 주의: 이 파일은 '새 스키마'다. reference/legacy/*.sql(레거시)은 참조자료일 뿐.
-- =============================================================================

-- 채번(전표번호) — 레거시 Max+1(동시성 없음, DB-51) 폐기 → 시퀀스
-- 접두어/날짜 포맷은 서비스 계층에서 조합(S/I/P/OUT). 여기선 순번만.
CREATE SEQUENCE seq_shipment_no;      -- S: 출고번호
CREATE SEQUENCE seq_invoice_no;       -- I: 매출번호
CREATE SEQUENCE seq_purge_no;         -- P: 폐기번호
CREATE SEQUENCE seq_consignment_no;   -- OUT: 위탁출고 원본번호

-- 거래처(최소) — FK 타깃용. 담보/여신/채권은 후속 Phase. 근거: custData
CREATE TABLE partners (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(20)  NOT NULL UNIQUE,
    name       VARCHAR(100) NOT NULL,
    type       VARCHAR(10)  NOT NULL DEFAULT 'NORMAL'
                 CHECK (type IN ('NORMAL','CONSIGN')),   -- 정상판매 / 후정산(위탁)
    created_at TIMESTAMP    NOT NULL,
    created_by VARCHAR(50),
    updated_at TIMESTAMP,
    updated_by VARCHAR(50)
);

-- 상품 — 근거: bookData(price/taxFree/grade/useYN) + 🆕 content_type/is_set
CREATE TABLE products (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(30)  NOT NULL UNIQUE,
    name         VARCHAR(100) NOT NULL,
    content_type VARCHAR(10)  NOT NULL
                   CHECK (content_type IN ('SELF','EXTERNAL')),  -- 🆕 자체교재/외부콘텐츠(순매출 계산 상이)
    is_set       BOOLEAN      NOT NULL DEFAULT FALSE,            -- 🆕 세트(BOM 완제품) 여부
    price        INTEGER,                                        -- 정가
    tax_free     BOOLEAN      NOT NULL DEFAULT FALSE,
    grade        VARCHAR(5),
    use_yn       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP    NOT NULL,
    created_by   VARCHAR(50),
    updated_at   TIMESTAMP,
    updated_by   VARCHAR(50)
);

-- BOM 구성 — 🆕 근거: 시트2 BOM 가변비율 (레거시 linkedCode 1:1 치환 대체)
-- 완제품(parent) 1개 = 구성품(child) ratio개
CREATE TABLE bom_items (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_product_id BIGINT  NOT NULL REFERENCES products(id),
    child_product_id  BIGINT  NOT NULL REFERENCES products(id),
    ratio             INTEGER NOT NULL CHECK (ratio > 0),
    created_at        TIMESTAMP NOT NULL,
    created_by        VARCHAR(50),
    updated_at        TIMESTAMP,
    updated_by        VARCHAR(50),
    UNIQUE (parent_product_id, child_product_id)
);

-- 창고 — 🆕 근거: 시트2① (레거시 창고 컬럼 전 테이블 0건, DB-22)
CREATE TABLE warehouses (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(20) NOT NULL UNIQUE,
    name       VARCHAR(50) NOT NULL,
    type       VARCHAR(10) NOT NULL
                 CHECK (type IN ('MAIN','CONSIGN')),   -- MAIN=본사 물류창고(실물) / CONSIGN=위탁창고(가상)
    created_at TIMESTAMP   NOT NULL,
    created_by VARCHAR(50),
    updated_at TIMESTAMP,
    updated_by VARCHAR(50)
);

-- 재고 원장(잔량) — 🆕 상품×창고 단위. 음수재고 방지.
CREATE TABLE inventory (
    id           BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   BIGINT  NOT NULL REFERENCES products(id),
    warehouse_id BIGINT  NOT NULL REFERENCES warehouses(id),
    qty          INTEGER NOT NULL DEFAULT 0 CHECK (qty >= 0),  -- 🆕 음수재고 방지(불변식)
    created_at   TIMESTAMP NOT NULL,
    created_by   VARCHAR(50),
    updated_at   TIMESTAMP,
    updated_by   VARCHAR(50),
    UNIQUE (product_id, warehouse_id)
);

-- 재고 이벤트 — 근거: InvenData 정규화 + 🆕 창고/원가/txn_type
-- qty는 부호 포함(입고/반품 +, 출고/폐기 -). 창고 잔량 = 해당 상품×창고 txn qty 합.
-- 이동(TRANSFER)·BOM은 두 행 이상으로 표현, source_txn_id로 연결.
CREATE TABLE inventory_txn (
    id            BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT  NOT NULL REFERENCES products(id),
    warehouse_id  BIGINT  NOT NULL REFERENCES warehouses(id),
    txn_type      VARCHAR(20) NOT NULL
                    CHECK (txn_type IN ('INBOUND','OUTBOUND','TRANSFER',
                                        'BOM_ASSEMBLE','BOM_DISASSEMBLE','DISPOSE','RETURN')),
    qty           INTEGER NOT NULL,          -- 부호 포함
    unit_cost     BIGINT,                    -- 🆕 입고원가(순매출/이익률용, 레거시 부재 BE-20)
    ref_no        VARCHAR(30),               -- 전표번호(S/OUT 등)
    trade_date    DATE    NOT NULL,          -- 🆕 varchar→DATE 정규화(DB-08)
    source_txn_id BIGINT  REFERENCES inventory_txn(id),  -- 이고/BOM 짝 연결
    partner_id    BIGINT  REFERENCES partners(id),
    memo          VARCHAR(1000),
    created_at    TIMESTAMP NOT NULL,
    created_by    VARCHAR(50),
    updated_at    TIMESTAMP,
    updated_by    VARCHAR(50)
);
CREATE INDEX ix_inv_txn_prod_wh   ON inventory_txn (product_id, warehouse_id);
CREATE INDEX ix_inv_txn_trade_dt  ON inventory_txn (trade_date);

-- 출고유형(6) → 회계구분(3) 룩업 — 근거: 시트2① (레거시 하드코딩 CASE, DB-25)
-- ※ '취소'의 공급률 30% 분기(매출/무가/유가)는 서비스 로직에서 처리.
CREATE TABLE out_type_mapping (
    out_type        VARCHAR(20) PRIMARY KEY   -- ShipmentType(출고유형)
                      CHECK (out_type IN ('NORMAL_SHIP','CONSIGN_SHIP','GIFT','TEACHER_USE','RETURN','CANCEL')),
    acct_type       VARCHAR(10) NOT NULL      -- SalesCategory(회계구분)
                      CHECK (acct_type IN ('SALE','FREE','RETURN')),
    default_wh_type VARCHAR(10) NOT NULL
                      CHECK (default_wh_type IN ('MAIN','CONSIGN')),
    is_consignment  BOOLEAN     NOT NULL DEFAULT FALSE
);
INSERT INTO out_type_mapping (out_type, acct_type, default_wh_type, is_consignment) VALUES
    ('NORMAL_SHIP' , 'SALE'  , 'MAIN'   , FALSE),  -- 정상출고: 즉시 매출
    ('CONSIGN_SHIP', 'SALE'  , 'CONSIGN', TRUE ),  -- 위탁출고: 위탁창고 이동 + 매출 미결
    ('GIFT'        , 'FREE'  , 'MAIN'   , FALSE),  -- 증정용: 무상
    ('TEACHER_USE' , 'FREE'  , 'MAIN'   , FALSE),  -- 교사용: 무상
    ('RETURN'      , 'RETURN', 'MAIN'   , FALSE),  -- 반품: 물류창고 복귀
    ('CANCEL'      , 'RETURN', 'MAIN'   , FALSE);  -- 취소: 회계상 반품(공급률 분기는 로직)

-- 위탁 미결원장 — 🆕 근거: 로직B (BE-30~35). 불변식/초과정산 방지 제약.
CREATE TABLE consignment_out (
    id            BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_out_no VARCHAR(30) NOT NULL UNIQUE,   -- OUT-YYYYMMDD-nn
    product_id    BIGINT  NOT NULL REFERENCES products(id),
    partner_id    BIGINT  NOT NULL REFERENCES partners(id),
    total_qty     INTEGER NOT NULL CHECK (total_qty > 0),
    settled_qty   INTEGER NOT NULL DEFAULT 0 CHECK (settled_qty >= 0),
    remaining_qty INTEGER NOT NULL,
    status        VARCHAR(10) NOT NULL DEFAULT 'OPEN'
                    CHECK (status IN ('OPEN','PARTIAL','CLOSED')),
    origin_txn_id BIGINT  REFERENCES inventory_txn(id),  -- 위탁출고 재고이벤트
    created_at    TIMESTAMP NOT NULL,
    created_by    VARCHAR(50),
    updated_at    TIMESTAMP,
    updated_by    VARCHAR(50),
    CONSTRAINT ck_consign_balance CHECK (total_qty = settled_qty + remaining_qty),  -- 🆕 불변식
    CONSTRAINT ck_consign_over    CHECK (settled_qty <= total_qty)                  -- 🆕 초과정산 방지
);
CREATE INDEX ix_consign_partner ON consignment_out (partner_id);
CREATE INDEX ix_consign_status  ON consignment_out (status);

-- 위탁 부분정산 이력 — 🆕 1건의 위탁출고에 대해 여러 차례 분할 정산
CREATE TABLE consignment_settlement (
    id                 BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consignment_out_id BIGINT  NOT NULL REFERENCES consignment_out(id),
    settle_qty         INTEGER NOT NULL CHECK (settle_qty > 0),
    sales_ref_no       VARCHAR(30),                 -- 매출 전표(I) — 매출 테이블은 후속 Phase
    settled_at         TIMESTAMP NOT NULL,
    created_at         TIMESTAMP NOT NULL,
    created_by         VARCHAR(50),
    updated_at         TIMESTAMP,
    updated_by         VARCHAR(50)
);
CREATE INDEX ix_settlement_consign ON consignment_settlement (consignment_out_id);
