-- =============================================================================
-- V2 — 매출 원장(확정 매출)
-- 근거: 기획서 P.12(통합매출조회)·P.13(매출등록) / API 스펙 §3
-- 설계: 미결(보류)은 sales가 아니라 consignment_out(OPEN/PARTIAL/CLOSED)이 '단일 진실'.
--       sales에는 '확정된 매출 라인'만 적재 — 정상출고 즉시 / 위탁정산 확정 시.
--       (스펙의 sales_ledger.status=PENDING_SETTLEMENT 개념 = 우리 consignment_out의 OPEN/PARTIAL)
-- =============================================================================

CREATE TABLE sales (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_no       VARCHAR(30) UNIQUE,           -- I-YYYYMMDD-nn (채번: seq_invoice_no)
    sales_date     DATE    NOT NULL,
    partner_id     BIGINT  NOT NULL REFERENCES partners(id),
    product_id     BIGINT  NOT NULL REFERENCES products(id),
    sales_type     VARCHAR(20) NOT NULL          -- 🆕 매출유형(독립 축): 일반/위탁매출
                     CHECK (sales_type IN ('NORMAL_SALES','CONSIGN_SALES')),
    shipment_type  VARCHAR(20) NOT NULL REFERENCES out_type_mapping(out_type),  -- 출고유형(6)
    sales_category VARCHAR(10) NOT NULL          -- 구분(회계): 매출/무상/반품
                     CHECK (sales_category IN ('SALE','FREE','RETURN')),
    unit_price     INTEGER,                      -- 정가
    supply_rate    INTEGER,                      -- 공급률(%)
    qty            INTEGER NOT NULL,             -- 수량(반품/취소는 음수)
    supply_amount  BIGINT,                       -- 공급가액
    tax            BIGINT,                       -- 세액
    total_amount   BIGINT,                       -- 총금액
    source_out_no  VARCHAR(30),                  -- 원본 위탁출고번호(위탁정산 매출일 때)
    settlement_id  BIGINT  REFERENCES consignment_settlement(id),  -- 위탁 정산 이력 링크
    memo           VARCHAR(1000),
    created_at     TIMESTAMP NOT NULL,
    created_by     VARCHAR(50),
    updated_at     TIMESTAMP,
    updated_by     VARCHAR(50)
);
CREATE INDEX ix_sales_partner ON sales (partner_id);
CREATE INDEX ix_sales_date    ON sales (sales_date);
CREATE INDEX ix_sales_product ON sales (product_id);
