-- 채권/수금 도메인(마감관리). 근거: 레거시 amtData/carrData/custData.assure + 기획서[마감관리]③④⑤.

-- 거래처 담보(여신) 컬럼
ALTER TABLE partners ADD COLUMN assure_amount BIGINT;      -- 담보금액(여신한도)
ALTER TABLE partners ADD COLUMN assure_expiry DATE;         -- 담보 만기
ALTER TABLE partners ADD COLUMN assure_note   VARCHAR(500); -- 담보 내용

-- 수금(amtData 정규화). collType=현금/어음/선수금/대체, collKind 고정 '도서대금'(레거시)
CREATE TABLE collection (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_no  VARCHAR(30) UNIQUE,          -- 채번(C-yyyyMMdd-seq), 레거시 Max+1 대체
    coll_date      DATE   NOT NULL,             -- 수금일자
    partner_id     BIGINT NOT NULL REFERENCES partners(id),
    coll_type      VARCHAR(20) NOT NULL
                     CHECK (coll_type IN ('CASH','PROMISSORY','PREPAY','REPLACE')),
    coll_amt       BIGINT NOT NULL CHECK (coll_amt >= 0),
    promissory_no      VARCHAR(50),             -- 어음번호(어음일 때)
    promissory_due     DATE,                    -- 어음 만기
    bank_name          VARCHAR(100),
    branch_name        VARCHAR(100),
    memo           VARCHAR(1000),
    created_at     TIMESTAMP NOT NULL,
    created_by     VARCHAR(50),
    updated_at     TIMESTAMP,
    updated_by     VARCHAR(50)
);
CREATE INDEX ix_collection_partner_date ON collection (partner_id, coll_date);
CREATE SEQUENCE seq_collection_no START 1;

-- 이월 스냅샷(carrData). 조회 부수효과 아님 — idempotent 배치/명시 API로만 생성.
-- carry_amount = 전년말 채권 잔액. (연도, 거래처) 유일.
CREATE TABLE receivable_carryforward (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fiscal_year   INTEGER NOT NULL,             -- 이월 귀속 연도(= 스냅샷 대상 연도)
    partner_id    BIGINT  NOT NULL REFERENCES partners(id),
    carry_amount  BIGINT  NOT NULL,
    generated_at  TIMESTAMP NOT NULL,
    created_at    TIMESTAMP NOT NULL,
    created_by    VARCHAR(50),
    updated_at    TIMESTAMP,
    updated_by    VARCHAR(50),
    CONSTRAINT uq_carryforward UNIQUE (fiscal_year, partner_id)
);
CREATE INDEX ix_carryforward_year ON receivable_carryforward (fiscal_year);
